layout_spectrum: 1
color:
  saturation: 0.7255639
  brandStrength: 0.1927048
  lightness: 0.01879696
  rhythmicContrast: 0.8931257
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.4570354
name: black monday
