analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.3614393
color:
  saturation: 0.6546724
  brandStrength: 0.3721804
  rhythmicContrast: 0.2604726
  brandColors:
    - '#020204'
    - '#646665'
    - '#9A9B9A'
  lightness: 0
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: black monday
typography_spectrum: 0.08324379
